### PR TITLE
Added FILESTAMP variable to disable timestamping log files.

### PR DESCRIPTION
**Pull request by HamAndChris**
For my application, I need to have complete control over the log file's name. It seemed like a pretty simple change while still keeping the "simple" philosophy of the library.

### CODE REVIEW

**Comment by GeoMEM** [comment]
This is an automated reply to your message "[slog] Added FILESTAMP variable to disable timestamping log files.
 (#7)" sent to james@geomem.com.

Dear chriszuma notifications@github.com

Thank you for your email. I am away from the office until 1st Sept 2015. I will have intermittent email access but will reply if I can.

If you have not received a reply within 48 hours please contact Irene Smith on irene.smith@geomem.com and/or sales@geomem.com. This email has NOT been forwarded.

For very urgent requirements please text (SMS message) me direct on +44 (0)7986 377 444.

Kind regards
James Tweedie
GeoMEM Ltd.
http://www.geomem.com

**Comment by HamAndChris** [comment]
Hello, I added another commit to this pull request. This one makes it so that when you have PRETTYLOG disabled, it still outputs the tag (INFO, WARN, etc.) in the file log. I also made a couple of safety and readability improvements to the areas of the code affected by this. Mostly changing sprintf's to snprintf's.

**Comment by GeoMEM** [comment]
This is an automated reply to your message "Re: [slog] Added FILESTAMP variable to disable timestamping log
 files. (#7)" sent to james@geomem.com.

Dear chriszuma notifications@github.com

Thank you for your email. I am away from the office until 1st Sept 2015. I will have intermittent email access but will reply if I can.

If you have not received a reply within 48 hours please contact Irene Smith on irene.smith@geomem.com and/or sales@geomem.com. This email has NOT been forwarded.

For very urgent requirements please text (SMS message) me direct on +44 (0)7986 377 444.

Kind regards
James Tweedie
GeoMEM Ltd.
http://www.geomem.com

**Comment by GeoMEM** [comment]
This is an automated reply to your message "Re: [slog] Added FILESTAMP variable to disable timestamping log
 files. (#7)" sent to james@geomem.com.

Dear Sun Dro notifications@github.com

Thank you for your email. I am away from the office until 1st Sept 2015. I will have intermittent email access but will reply if I can.

If you have not received a reply within 48 hours please contact Irene Smith on irene.smith@geomem.com and/or sales@geomem.com. This email has NOT been forwarded.

For very urgent requirements please text (SMS message) me direct on +44 (0)7986 377 444.

Kind regards
James Tweedie
GeoMEM Ltd.
http://www.geomem.com

**Comment by kala13x** [comment]
Thanks for this commit, I was working on that..
Toy are welcome :)

**Pull request merged**
