### PR TITLE
Code style cleanup, updated outdated examples.

### PR DESCRIPTION
**Pull request by GeorgeGkas**
This pull request does not provide any addition to the project implementation. Also we do not update any existing module or procedure. This pull request was created to update-clean the code style. After many contributions, we ended with different coding styles. For example conditional statements are used with different ways:

```c
if (something) {
    // ...do other
}
// after some lines
if (one)
{
    // .. add two
}

// after some more lines
if (1+3) printf("something");
else {
 // ...do nothing
}
```

I wanted to fix those "multi-styling" lines.

Also, we have cleaned the descriptions used in function prototypes. We passed from a verbal style to a more descriptive and simple one. In addition, we don't have to repeat the same informations both on the header and the source file. The purpose of the header file is to help the user to understand the API of a library. We added informations (such as function description, parameters and return value) that relates with the functionality and not with the implementation. We only have to add implementation informations on the source files. 

Lastly, we updated some outdated examples in the Readme file. 

Please consider to merge this pull request. For any additional informations, I'd love to read your comments.

### CODE REVIEW

**Comment by Burnett01** [comment]
Decent work I must say. Great job! :+1: 

Question out of scope: What is your editors indentation? I guess ``tabs`` of size ``2``?

**Comment by GeorgeGkas** [comment]
@Burnett01 I use sublime text editor 3 with some plugins to help me style the code. I use spaces to better support different editors and systems (not tabs). And indeed I used width of size 2 in this project. I usually like to set it to 4.

**Comment by Burnett01** [comment]
@kala13x You up to get this merged? :) :+1:

**Review by kala13x — COMMENTED** [review]
Great Job. Thanks

**Pull request merged**
